apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: my-registry-secret 
      containers:
        - name: myapp-container
          image: 192.168.20.30:5000/http_get_jenkins_nexus:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: my-config
            - secretRef:
                name: my-secret

